### PR TITLE
Move from REQUIRE to Project.toml

### PR DESCRIPTION
**Pull request by kescobo**

### CODE REVIEW

**Comment by kescobo** [comment]
@BenJWard This is failing because Travis doesn't know to get the latest version of `Microbiome` from the BioJuliaRegistry (I think). Any idea how to hook into that?

**Comment by TransGirlCodes** [comment]
@kescobo Ah yes I have dealt with this. So I edited my CI scripts to make sure they add the BioJuliaRegistry before they try to install or run anything. Have a look at how I did it with [FASTX.jl](https://github.com/BioJulia/FASTX.jl/blob/master/.travis.yml). Note how I run a script called ci_prep.jl - that's what makes sure all the registries that are used are added. I also do it explicitly later on in the travis config as well.

**Comment by kescobo** [comment]
@BenJWard Huh... the `using Pkg.Registry` bit doesn't work on `julia 1.0`. Are you just not supporting 1.0 with your packages? I see that's the case with FASTX.jl

**Comment by kescobo** [comment]
@bioreg `register()`

**Comment by TransGirlCodes** [comment]
Yeah, I just figured I'd just support from the present julia version onwards. It was sort of unavoidable anyway as it was only in a more recent version that Pkg functions for dealing with registries were introduced properly, trying to crowbar the previous version into doing the same without Pkg assistance felt like a hack.

**Pull request merged**
